apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-env
  labels:
    app.kubernetes.io/name: ruoyi
    app.kubernetes.io/part-of: ruoyi-cloud
    app.kubernetes.io/component: configuration
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/instance: ruoyi-env
  namespace: ruoyi
data:
  NACOS_ADDR: "nacos.ruoyi.svc.cluster.local:8848"
  NACOS_NAMESPACE: "public"
  NACOS_USERNAME: "nacos"
  NACOS_PASSWORD: "nacos"
  SENTINEL_ADDR: "sentinel.ruoyi.svc.cluster.local:8718"
  REDIS_ADDR: "redis-master.ruoyi.svc.cluster.local:6379"
  MYSQL_HOST: "mysql.ruoyi.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "ry-cloud"
  MYSQL_TIMEZONE: "+08:00"
  JAVA_OPTS: "-Xms512m -Xmx512m -Duser.timezone=Asia/Shanghai"
