apiVersion: v1
kind: Secret
metadata:
  name: ruoyi-mysql
  namespace: ruoyi
  labels:
    app.kubernetes.io/name: ruoyi-mysql
    app.kubernetes.io/part-of: ruoyi-cloud
type: Opaque
stringData:
  MYSQL_USER: ruoyi
  MYSQL_PASSWORD: ChangeMe@123
  MYSQL_ROOT_PASSWORD: ChangeMeRoot@123
