apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ruoyi
commonLabels:
  app.kubernetes.io/environment: prod
resources:
  - ../../base
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ruoyi
    path: ingress-hosts-patch.yaml
